source "https://rubygems.org"
ruby "2.7.1"
gem 'httparty'
gem 'dotenv'
gem "resque"
gem 'activerecord'
gem 'sinatra'
gem "sinatra-activerecord"
gem 'pg'
gem "activesupport"
gem "rake"
gem "redis"
gem 'pry'
